In [32]:
import pandas as pd
import numpy as np
import csv
import matplotlib as plt


c_names = ['vID', 'frID', 'tFr','Timestamp', 'localX', 'localY', 'globalX','globalY', 'vLenght', 'vWidth', 'vType', 'veloc','accel', 'line', 'pred', 'foll', 'spac', 'headway', 'dateTime']

data = pd.read_table('D:\\zzzLola\\PhD\\DataSet\\US101\\test\\portion1Set2DT.txt', sep='\t', header=None, names=c_names)

# Stast description of the whole dataset.
desc = data.describe()

In [33]:
desc

,vID,frID,tFr,Timestamp,localX,localY,globalX,globalY,vLenght,vWidth,vType,veloc,accel,line,pred,foll,spac,headway
count,1597.000000,1597.000000,1597.000000,1.597000e+03,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000
mean,4.182843,267.204133,404.460238,1.118847e+12,40.166214,1114.140043,6451915.031800,1872594.324443,15.425485,5.749092,2,46.853181,0.427790,3.865373,0.706324,9.244208,11.302549,0.241935
std,1.496573,123.996664,45.413270,1.239967e+04,18.506289,559.918912,419.122022,372.802068,1.209852,1.351837,0,7.709628,4.989681,1.647519,1.525733,3.987194,24.613803,0.523286
min,2.000000,8.000000,351.000000,1.118847e+12,6.263000,35.381000,6451122.815000,1871894.687000,14.000000,4.900000,2,32.640000,-11.200000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,172.000000,357.000000,1.118847e+12,17.813000,664.639000,6451572.038000,1872291.603000,14.500000,4.900000,2,40.710000,-1.460000,2.000000,0.000000,6.000000,0.000000,0.000000
50%,5.000000,272.000000,437.000000,1.118847e+12,42.818000,1102.629000,6451903.487000,1872598.226000,16.000000,4.900000,2,45.000000,0.000000,4.000000,0.000000,8.000000,0.000000,0.000000
75%,5.000000,371.000000,452.000000,1.118847e+12,54.753000,1572.348000,6452258.323000,1872883.465000,17.000000,7.900000,2,51.360000,2.660000,5.000000,0.000000,13.000000,0.000000,0.000000
max,6.000000,497.000000,452.000000,1.118847e+12,71.498000,2161.090000,6452704.608000,1873344.962000,17.000000,7.900000,2,70.030000,11.200000,7.000000,4.000000,18.000000,78.580000,1.500000

In [34]:
data[:50]

,vID,frID,tFr,Timestamp,localX,localY,globalX,globalY,vLenght,vWidth,vType,veloc,accel,line,pred,foll,spac,headway,dateTime
0,2,13,437,1118846980200,16.467,35.381,6451137.641,1873344.962,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
1,2,14,437,1118846980300,16.447,39.381,6451140.329,1873342.000,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
2,2,15,437,1118846980400,16.426,43.381,6451143.018,1873339.038,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
3,2,16,437,1118846980500,16.405,47.380,6451145.706,1873336.077,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
4,2,17,437,1118846980600,16.385,51.381,6451148.395,1873333.115,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
5,2,18,437,1118846980700,16.364,55.381,6451151.084,1873330.153,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
6,2,19,437,1118846980800,16.344,59.381,6451153.772,1873327.192,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
7,2,20,437,1118846980900,16.323,63.379,6451156.461,1873324.230,14.5,4.9,2,40.02,0.25,2,0,0,0,0,2005-06-15 14:49:40
8,2,21,437,1118846981000,16.303,67.383,6451159.149,1873321.268,14.5,4.9,2,40.03,0.13,2,0,0,0,0,2005-06-15 14:49:41
9,2,22,437,1118846981100,16.282,71.398,6451161.838,1873318.307,14.5,4.9,2,39.93,-1.63,2,0,13,0,0,2005-06-15 14:49:41
10,2,23,437,1118846981200,16.262,75.401,6451164.546,1873315.323,14.5,4.9,2,39.61,-4.54,2,0,13,0,0,2005-06-15 14:49:41
11,2,24,437,1118846981300,16.254,79.349,6451167.199,1873312.382,14.5,4.9,2,39.14,-5.73,2,0,13,0,0,2005-06-15 14:49:41
12,2,25,437,1118846981400,16.221,83.233,6451169.802,1873309.533,14.5,4.9,2,38.61,-5.15,2,0,13,0,0,2005-06-15 14:49:41
13,2,26,437,1118846981500,16.201,87.043,6451172.358,1873306.719,14.5,4.9,2,38.28,-1.61,2,0,13,0,0,2005-06-15 14:49:41
14,2,27,437,1118846981600,16.169,90.829,6451174.961,1873303.870,14.5,4.9,2,38.42,3.73,2,0,13,0,0,2005-06-15 14:49:41
15,2,28,437,1118846981700,16.204,94.683,6451177.613,1873300.929,14.5,4.9,2,38.78,4.86,2,0,13,0,0,2005-06-15 14:49:41
16,2,29,437,1118846981800,16.252,98.611,6451180.342,1873297.924,14.5,4.9,2,38.92,0.00,2,0,13,0,0,2005-06-15 14:49:41
17,2,30,437,1118846981900,16.339,102.560,6451182.980,1873294.961,14.5,4.9,2,38.54,-8.59,2,0,13,0,0,2005-06-15 14:49:41
18,2,31,437,1118846982000,16.400,106.385,6451185.537,1873292.122,14.5,4.9,2,37.51,-11.20,2,0,13,0,0,2005-06-15 14:49:42
19,2,32,437,1118846982100,16.430,110.079,6451188.021,1873289.408,14.5,4.9,2,36.34,-10.86,2,0,13,0,0,2005-06-15 14:49:42
20,2,33,437,1118846982200,16.435,113.628,6451190.424,1873286.817,14.5,4.9,2,35.50,-6.20,2,0,13,0,0,2005-06-15 14:49:42
21,2,34,437,1118846982300,16.478,117.118,6451192.757,1873284.247,14.5,4.9,2,35.08,-1.89,2,0,13,0,0,2005-06-15 14:49:42
22,2,35,437,1118846982400,16.520,120.600,6451195.109,1873281.656,14.5,4.9,2,34.96,0.18,2,0,13,0,0,2005-06-15 14:49:42
23,2,36,437,1118846982500,16.562,124.096,6451197.462,1873279.065,14.5,4.9,2,34.98,0.25,2,0,13,0,0,2005-06-15 14:49:42
24,2,37,437,1118846982600,16.605,127.597,6451199.814,1873276.473,14.5,4.9,2,35.00,0.04,2,0,13,0,0,2005-06-15 14:49:42
25,2,38,437,1118846982700,16.647,131.099,6451202.167,1873273.882,14.5,4.9,2,34.99,-0.20,2,0,13,0,0,2005-06-15 14:49:42
26,2,39,437,1118846982800,16.691,134.595,6451204.519,1873271.290,14.5,4.9,2,34.98,-0.02,2,0,13,0,0,2005-06-15 14:49:42
27,2,40,437,1118846982900,16.727,138.081,6451206.879,1873268.700,14.5,4.9,2,35.10,1.95,2,0,13,0,0,2005-06-15 14:49:42
28,2,41,437,1118846983000,16.796,141.578,6451209.191,1873266.113,14.5,4.9,2,35.49,5.55,2,0,13,0,0,2005-06-15 14:49:43
29,2,42,437,1118846983100,16.795,145.131,6451211.610,1873263.514,14.5,4.9,2,36.20,8.99,2,0,13,0,0,2005-06-15 14:49:43
30,2,43,437,1118846983200,16.724,148.784,6451214.156,1873260.882,14.5,4.9,2,37.15,10.44,2,0,13,0,0,2005-06-15 14:49:43
31,2,44,437,1118846983300,16.588,152.559,6451216.824,1873258.213,14.5,4.9,2,38.12,9.30,2,0,13,0,0,2005-06-15 14:49:43
32,2,45,437,1118846983400,16.376,156.449,6451219.616,1873255.522,14.5,4.9,2,38.76,4.36,2,0,13,0,0,2005-06-15 14:49:43
33,2,46,437,1118846983500,16.064,160.379,6451222.548,1873252.829,14.5,4.9,2,38.95,-0.73,2,0,13,0,0,2005-06-15 14:49:43
34,2,47,437,1118846983600,15.763,164.277,6451225.462,1873250.139,14.5,4.9,2,38.95,-1.15,2,0,13,0,0,2005-06-15 14:49:43
35,2,48,437,1118846983700,15.471,168.150,6451228.376,1873247.450,14.5,4.9,2,38.99,1.90,2,0,13,0,0,2005-06-15 14:49:43
36,2,49,437,1118846983800,15.226,172.044,6451231.290,1873244.760,14.5,4.9,2,39.18,3.47,2,0,13,0,0,2005-06-15 14:49:43
37,2,50,437,1118846983900,14.979,176.000,6451234.204,1873242.071,14.5,4.9,2,39.34,0.02,2,0,13,0,0,2005-06-15 14:49:43
38,2,51,437,1118846984000,14.720,179.959,6451237.144,1873239.374,14.5,4.9,2,39.20,-3.52,2,0,13,0,0,2005-06-15 14:49:44
39,2,52,437,1118846984100,14.508,183.862,6451239.988,1873236.708,14.5,4.9,2,38.89,-3.28,2,0,13,0,0,2005-06-15 14:49:44
40,2,53,437,1118846984200,14.331,187.716,6451242.770,1873234.057,14.5,4.9,2,38.73,-0.33,2,0,13,0,0,2005-06-15 14:49:44
41,2,54,437,1118846984300,14.240,191.561,6451245.501,1873231.336,14.5,4.9,2,38.88,3.49,2,0,13,0,0,2005-06-15 14:49:44
42,2,55,437,1118846984400,14.309,195.455,6451248.125,1873228.494,14.5,4.9,2,39.28,5.00,2,0,13,0,0,2005-06-15 14:49:44
43,2,56,437,1118846984500,14.428,199.414,6451250.788,1873225.539,14.5,4.9,2,39.68,3.76,2,0,13,0,0,2005-06-15 14:49:44
44,2,57,437,1118846984600,14.540,203.417,6451253.489,1873222.554,14.5,4.9,2,39.94,1.29,2,0,13,0,0,2005-06-15 14:49:44
45,2,58,437,1118846984700,14.646,207.430,6451256.177,1873219.592,14.5,4.9,2,40.02,-0.22,2,0,13,0,0,2005-06-15 14:49:44
46,2,59,437,1118846984800,14.751,211.431,6451258.866,1873216.630,14.5,4.9,2,40.00,-0.21,2,0,13,0,0,2005-06-15 14:49:44
47,2,60,437,1118846984900,14.856,215.428,6451261.554,1873213.669,14.5,4.9,2,39.99,0.00,2,0,13,0,0,2005-06-15 14:49:44
48,2,61,437,1118846985000,14.962,219.427,6451264.243,1873210.707,14.5,4.9,2,39.99,0.00,2,0,13,0,0,2005-06-15 14:49:45
49,2,62,437,1118846985100,15.067,223.462,6451266.932,1873207.745,14.5,4.9,2,39.65,-5.35,2,0,13,0,0,2005-06-15 14:49:45

In [35]:
ts1 = data[19:25]

In [36]:
ts2 = data[19:26]

In [37]:
ts1

,vID,frID,tFr,Timestamp,localX,localY,globalX,globalY,vLenght,vWidth,vType,veloc,accel,line,pred,foll,spac,headway,dateTime
19,2,32,437,1118846982100,16.430,110.079,6451188.021,1873289.408,14.5,4.9,2,36.34,-10.86,2,0,13,0,0,2005-06-15 14:49:42
20,2,33,437,1118846982200,16.435,113.628,6451190.424,1873286.817,14.5,4.9,2,35.50,-6.20,2,0,13,0,0,2005-06-15 14:49:42
21,2,34,437,1118846982300,16.478,117.118,6451192.757,1873284.247,14.5,4.9,2,35.08,-1.89,2,0,13,0,0,2005-06-15 14:49:42
22,2,35,437,1118846982400,16.520,120.600,6451195.109,1873281.656,14.5,4.9,2,34.96,0.18,2,0,13,0,0,2005-06-15 14:49:42
23,2,36,437,1118846982500,16.562,124.096,6451197.462,1873279.065,14.5,4.9,2,34.98,0.25,2,0,13,0,0,2005-06-15 14:49:42
24,2,37,437,1118846982600,16.605,127.597,6451199.814,1873276.473,14.5,4.9,2,35.00,0.04,2,0,13,0,0,2005-06-15 14:49:42

In [7]:
data(12:19)

SyntaxError: invalid syntax (<ipython-input-7-e30932e2ca69>, line 1)

In [8]:
data[(12:19)]

SyntaxError: invalid syntax (<ipython-input-8-a09065cf9c5e>, line 1)

In [9]:
data.iloc[[16]]

,vID,frID,tFr,Timestamp,localX,localY,globalX,globalY,vLenght,vWidth,vType,veloc,accel,line,pred,foll,spac,headway,dateTime
16,2,29,437,1118846981800,16.252,98.611,6451180.342,1873297.924,14.5,4.9,2,38.92,0,2,0,13,0,0,2005-06-15 14:49:41

In [12]:
data.at[[16, 19]]

ValueError: Invalid call for scalar access (getting)!

In [40]:
dt1 = data.iat[16, 18]

In [41]:
dt2 = data.iat[25, 18]

In [42]:
dt1

'2005-06-15 14:49:41'

In [43]:
dt2

'2005-06-15 14:49:42'

In [15]:
from datetime import datetime

date_object1 = datetime.strptime(dt1, "%Y-%m-%d %H:%M:%S")

In [16]:
date_object2 = datetime.strptime(dt2, "%Y-%m-%d %H:%M:%S")

In [30]:
date_object1

datetime.datetime(2005, 6, 15, 14, 49, 41)

In [17]:
date_object2

datetime.datetime(2005, 6, 15, 14, 49, 42)

In [18]:
delta = date_object2 - date_object1
delta.total_seconds()

1.0

In [21]:
v = 0
t = 0
for line in data:
    vID = line[0]
    if v == vID:
        dt = datetime.strptime(line[v,18], "%Y-%m-%d %H:%M:%S")
        if dt > t:
            d_max = dt
            t = dt
    print d_max

NameError: name 'd_max' is not defined

In [30]:
v = 0
t = 0
time_list = []
for line in data:
    vID = data.iat[int(line),0]
    if data.iat[int(line+1),0]:
        print data.iat[int(line+1),0]
    print vID
    if v == vID:
        time = data[3]
        while (number != -1):
            num_list.append(time)
            number = int(time)
        t_max = max(time)
        t_min = min(time)
        print (v, t_max, t_min)

ValueError: iAt based indexing can only have integer indexers

In [61]:
for i, row in data.iterrows():
    vID = data.irow(i)['vID']
    if data.irow(i+1)['vID']:
        vID1 = data.irow(i+1)['vID']
        print vID, vID1

2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 4
4 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 5
5 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: irow(i) is deprecated. Please use .iloc[i]
  from ipykernel import kernelapp as app
C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: irow(i) is deprecated. Please use .iloc[i]
  app.launch_new_instance()
C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: FutureWarning: irow(i) is deprecated. Please use .iloc[i]

IndexError: index 1597 is out of bounds for axis 0 with size 1597

In [ ]:
for