In [1]:
#%matplotlib inline

from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import csv
import matplotlib as plt

In [2]:
c_names = ['vID', 'frID', 'tFr','Timestamp', 'localX', 'localY', 'globalX','globalY', 'vLenght', 'vWidth', 'vType', 
           'veloc','accel', 'line', 'pred', 'foll', 'spac', 'headway', 'dateTime']

In [3]:
data = pd.read_table('D:\\zzzLola\\PhD\\DataSet\\US101\\test\\dataset1DT.txt', sep='\t', header=None, names=c_names)

In [4]:
data[:50]

,vID,frID,tFr,Timestamp,localX,localY,globalX,globalY,vLenght,vWidth,vType,veloc,accel,line,pred,foll,spac,headway,dateTime
0,2,13,437,1118846980200,16.467,35.381,6451137.641,1873344.962,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
1,2,14,437,1118846980300,16.447,39.381,6451140.329,1873342.000,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
2,2,15,437,1118846980400,16.426,43.381,6451143.018,1873339.038,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
3,2,16,437,1118846980500,16.405,47.380,6451145.706,1873336.077,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
4,2,17,437,1118846980600,16.385,51.381,6451148.395,1873333.115,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
5,2,18,437,1118846980700,16.364,55.381,6451151.084,1873330.153,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
6,2,19,437,1118846980800,16.344,59.381,6451153.772,1873327.192,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
7,2,20,437,1118846980900,16.323,63.379,6451156.461,1873324.230,14.5,4.9,2,40.02,0.25,2,0,0,0,0,2005-06-15 14:49:40
8,2,21,437,1118846981000,16.303,67.383,6451159.149,1873321.268,14.5,4.9,2,40.03,0.13,2,0,0,0,0,2005-06-15 14:49:41
9,2,22,437,1118846981100,16.282,71.398,6451161.838,1873318.307,14.5,4.9,2,39.93,-1.63,2,0,13,0,0,2005-06-15 14:49:41
10,2,23,437,1118846981200,16.262,75.401,6451164.546,1873315.323,14.5,4.9,2,39.61,-4.54,2,0,13,0,0,2005-06-15 14:49:41
11,2,24,437,1118846981300,16.254,79.349,6451167.199,1873312.382,14.5,4.9,2,39.14,-5.73,2,0,13,0,0,2005-06-15 14:49:41
12,2,25,437,1118846981400,16.221,83.233,6451169.802,1873309.533,14.5,4.9,2,38.61,-5.15,2,0,13,0,0,2005-06-15 14:49:41
13,2,26,437,1118846981500,16.201,87.043,6451172.358,1873306.719,14.5,4.9,2,38.28,-1.61,2,0,13,0,0,2005-06-15 14:49:41
14,2,27,437,1118846981600,16.169,90.829,6451174.961,1873303.870,14.5,4.9,2,38.42,3.73,2,0,13,0,0,2005-06-15 14:49:41
15,2,28,437,1118846981700,16.204,94.683,6451177.613,1873300.929,14.5,4.9,2,38.78,4.86,2,0,13,0,0,2005-06-15 14:49:41
16,2,29,437,1118846981800,16.252,98.611,6451180.342,1873297.924,14.5,4.9,2,38.92,0.00,2,0,13,0,0,2005-06-15 14:49:41
17,2,30,437,1118846981900,16.339,102.560,6451182.980,1873294.961,14.5,4.9,2,38.54,-8.59,2,0,13,0,0,2005-06-15 14:49:41
18,2,31,437,1118846982000,16.400,106.385,6451185.537,1873292.122,14.5,4.9,2,37.51,-11.20,2,0,13,0,0,2005-06-15 14:49:42
19,2,32,437,1118846982100,16.430,110.079,6451188.021,1873289.408,14.5,4.9,2,36.34,-10.86,2,0,13,0,0,2005-06-15 14:49:42
20,2,33,437,1118846982200,16.435,113.628,6451190.424,1873286.817,14.5,4.9,2,35.50,-6.20,2,0,13,0,0,2005-06-15 14:49:42
21,2,34,437,1118846982300,16.478,117.118,6451192.757,1873284.247,14.5,4.9,2,35.08,-1.89,2,0,13,0,0,2005-06-15 14:49:42
22,2,35,437,1118846982400,16.520,120.600,6451195.109,1873281.656,14.5,4.9,2,34.96,0.18,2,0,13,0,0,2005-06-15 14:49:42
23,2,36,437,1118846982500,16.562,124.096,6451197.462,1873279.065,14.5,4.9,2,34.98,0.25,2,0,13,0,0,2005-06-15 14:49:42
24,2,37,437,1118846982600,16.605,127.597,6451199.814,1873276.473,14.5,4.9,2,35.00,0.04,2,0,13,0,0,2005-06-15 14:49:42
25,2,38,437,1118846982700,16.647,131.099,6451202.167,1873273.882,14.5,4.9,2,34.99,-0.20,2,0,13,0,0,2005-06-15 14:49:42
26,2,39,437,1118846982800,16.691,134.595,6451204.519,1873271.290,14.5,4.9,2,34.98,-0.02,2,0,13,0,0,2005-06-15 14:49:42
27,2,40,437,1118846982900,16.727,138.081,6451206.879,1873268.700,14.5,4.9,2,35.10,1.95,2,0,13,0,0,2005-06-15 14:49:42
28,2,41,437,1118846983000,16.796,141.578,6451209.191,1873266.113,14.5,4.9,2,35.49,5.55,2,0,13,0,0,2005-06-15 14:49:43
29,2,42,437,1118846983100,16.795,145.131,6451211.610,1873263.514,14.5,4.9,2,36.20,8.99,2,0,13,0,0,2005-06-15 14:49:43
30,2,43,437,1118846983200,16.724,148.784,6451214.156,1873260.882,14.5,4.9,2,37.15,10.44,2,0,13,0,0,2005-06-15 14:49:43
31,2,44,437,1118846983300,16.588,152.559,6451216.824,1873258.213,14.5,4.9,2,38.12,9.30,2,0,13,0,0,2005-06-15 14:49:43
32,2,45,437,1118846983400,16.376,156.449,6451219.616,1873255.522,14.5,4.9,2,38.76,4.36,2,0,13,0,0,2005-06-15 14:49:43
33,2,46,437,1118846983500,16.064,160.379,6451222.548,1873252.829,14.5,4.9,2,38.95,-0.73,2,0,13,0,0,2005-06-15 14:49:43
34,2,47,437,1118846983600,15.763,164.277,6451225.462,1873250.139,14.5,4.9,2,38.95,-1.15,2,0,13,0,0,2005-06-15 14:49:43
35,2,48,437,1118846983700,15.471,168.150,6451228.376,1873247.450,14.5,4.9,2,38.99,1.90,2,0,13,0,0,2005-06-15 14:49:43
36,2,49,437,1118846983800,15.226,172.044,6451231.290,1873244.760,14.5,4.9,2,39.18,3.47,2,0,13,0,0,2005-06-15 14:49:43
37,2,50,437,1118846983900,14.979,176.000,6451234.204,1873242.071,14.5,4.9,2,39.34,0.02,2,0,13,0,0,2005-06-15 14:49:43
38,2,51,437,1118846984000,14.720,179.959,6451237.144,1873239.374,14.5,4.9,2,39.20,-3.52,2,0,13,0,0,2005-06-15 14:49:44
39,2,52,437,1118846984100,14.508,183.862,6451239.988,1873236.708,14.5,4.9,2,38.89,-3.28,2,0,13,0,0,2005-06-15 14:49:44
40,2,53,437,1118846984200,14.331,187.716,6451242.770,1873234.057,14.5,4.9,2,38.73,-0.33,2,0,13,0,0,2005-06-15 14:49:44
41,2,54,437,1118846984300,14.240,191.561,6451245.501,1873231.336,14.5,4.9,2,38.88,3.49,2,0,13,0,0,2005-06-15 14:49:44
42,2,55,437,1118846984400,14.309,195.455,6451248.125,1873228.494,14.5,4.9,2,39.28,5.00,2,0,13,0,0,2005-06-15 14:49:44
43,2,56,437,1118846984500,14.428,199.414,6451250.788,1873225.539,14.5,4.9,2,39.68,3.76,2,0,13,0,0,2005-06-15 14:49:44
44,2,57,437,1118846984600,14.540,203.417,6451253.489,1873222.554,14.5,4.9,2,39.94,1.29,2,0,13,0,0,2005-06-15 14:49:44
45,2,58,437,1118846984700,14.646,207.430,6451256.177,1873219.592,14.5,4.9,2,40.02,-0.22,2,0,13,0,0,2005-06-15 14:49:44
46,2,59,437,1118846984800,14.751,211.431,6451258.866,1873216.630,14.5,4.9,2,40.00,-0.21,2,0,13,0,0,2005-06-15 14:49:44
47,2,60,437,1118846984900,14.856,215.428,6451261.554,1873213.669,14.5,4.9,2,39.99,0.00,2,0,13,0,0,2005-06-15 14:49:44
48,2,61,437,1118846985000,14.962,219.427,6451264.243,1873210.707,14.5,4.9,2,39.99,0.00,2,0,13,0,0,2005-06-15 14:49:45
49,2,62,437,1118846985100,15.067,223.462,6451266.932,1873207.745,14.5,4.9,2,39.65,-5.35,2,0,13,0,0,2005-06-15 14:49:45

In [5]:
v_ts = DataFrame(data, columns=['vID', 'Timestamp'])

In [6]:
v_dt = DataFrame(data, columns=['vID', 'dateTime'])

In [7]:
v_ts[:10]

   vID      Timestamp
0    2  1118846980200
1    2  1118846980300
2    2  1118846980400
3    2  1118846980500
4    2  1118846980600
5    2  1118846980700
6    2  1118846980800
7    2  1118846980900
8    2  1118846981000
9    2  1118846981100

In [8]:
v_dt[:10]

   vID             dateTime
0    2  2005-06-15 14:49:40
1    2  2005-06-15 14:49:40
2    2  2005-06-15 14:49:40
3    2  2005-06-15 14:49:40
4    2  2005-06-15 14:49:40
5    2  2005-06-15 14:49:40
6    2  2005-06-15 14:49:40
7    2  2005-06-15 14:49:40
8    2  2005-06-15 14:49:41
9    2  2005-06-15 14:49:41

In [9]:
v_ts_gr = v_ts.groupby(['Timestamp']).size()
v_ts_gr

Timestamp
1118846979700    1
1118846979800    1
1118846979900    1
1118846980000    1
1118846980100    1
1118846980200    2
1118846980300    2
1118846980400    2
1118846980500    2
1118846980600    2
1118846980700    2
1118846980800    2
1118846980900    2
1118846981000    2
1118846981100    3
1118846981200    3
1118846981300    3
1118846981400    3
1118846981500    3
1118846981600    3
1118846981700    3
1118846981800    4
1118846981900    4
1118846982000    4
1118846982100    5
1118846982200    5
1118846982300    5
1118846982400    5
1118846982500    5
1118846982600    6
                ..
1118847929600    1
1118847929700    1
1118847929800    1
1118847929900    1
1118847930000    1
1118847930100    1
1118847930200    1
1118847930300    1
1118847930400    1
1118847930500    1
1118847930600    1
1118847930700    1
1118847930800    1
1118847930900    1
1118847931000    1
1118847931100    1
1118847931200    1
1118847931300    1
1118847931400    1
1118847931500    1
1118847931600    1
1118847931700    1
1118847931800    1
1118847931900    1
1118847932000    1
1118847932100    1
1118847932200    1
1118847932300    1
1118847932400    1
1118847932500    1
dtype: int64

In [10]:
v_ts_gr.max()

194

In [11]:
v_ts_gr.min()

1

In [12]:
v_dt_gr = v_dt.groupby(['dateTime']).size()
v_dt_gr

dateTime
2005-06-15 14:49:39      3
2005-06-15 14:49:40     18
2005-06-15 14:49:41     31
2005-06-15 14:49:42     55
2005-06-15 14:49:43     81
2005-06-15 14:49:44    118
2005-06-15 14:49:45    142
2005-06-15 14:49:46    167
2005-06-15 14:49:47    184
2005-06-15 14:49:48    210
2005-06-15 14:49:49    231
2005-06-15 14:49:50    257
2005-06-15 14:49:51    291
2005-06-15 14:49:52    326
2005-06-15 14:49:53    371
2005-06-15 14:49:54    407
2005-06-15 14:49:55    428
2005-06-15 14:49:56    466
2005-06-15 14:49:57    489
2005-06-15 14:49:58    528
2005-06-15 14:49:59    558
2005-06-15 14:50:00    580
2005-06-15 14:50:01    610
2005-06-15 14:50:02    631
2005-06-15 14:50:03    660
2005-06-15 14:50:04    687
2005-06-15 14:50:05    727
2005-06-15 14:50:06    754
2005-06-15 14:50:07    780
2005-06-15 14:50:08    820
                      ...
2005-06-15 15:05:03    607
2005-06-15 15:05:04    594
2005-06-15 15:05:05    551
2005-06-15 15:05:06    519
2005-06-15 15:05:07    495
2005-06-15 15:05:08    475
2005-06-15 15:05:09    453
2005-06-15 15:05:10    440
2005-06-15 15:05:11    419
2005-06-15 15:05:12    392
2005-06-15 15:05:13    378
2005-06-15 15:05:14    348
2005-06-15 15:05:15    322
2005-06-15 15:05:16    290
2005-06-15 15:05:17    270
2005-06-15 15:05:18    256
2005-06-15 15:05:19    230
2005-06-15 15:05:20    214
2005-06-15 15:05:21    179
2005-06-15 15:05:22    159
2005-06-15 15:05:23    134
2005-06-15 15:05:24    117
2005-06-15 15:05:25     87
2005-06-15 15:05:26     48
2005-06-15 15:05:27     35
2005-06-15 15:05:28     19
2005-06-15 15:05:29     10
2005-06-15 15:05:30     10
2005-06-15 15:05:31     10
2005-06-15 15:05:32      6
dtype: int64

In [13]:
v_dt_gr.max()

1926

In [14]:
v_dt_gr.min()

3

In [15]:
data_mean = data.groupby(['vID', 'dateTime']).mean()

In [16]:
data_mean #Mean values for the data grouped by vID and dateTime

                            frID  tFr     Timestamp     localX       localY  \
vID  dateTime
2    2005-06-15 14:49:40    16.5  437  1.118847e+12  16.395125    49.380625
     2005-06-15 14:49:41    25.5  437  1.118847e+12  16.248700    85.049000
     2005-06-15 14:49:42    35.5  437  1.118847e+12  16.549500   122.327800
     2005-06-15 14:49:43    45.5  437  1.118847e+12  16.078200   158.535100
     2005-06-15 14:49:44    55.5  437  1.118847e+12  14.532900   197.567300
     2005-06-15 14:49:45    65.5  437  1.118847e+12  15.562200   237.208600
     2005-06-15 14:49:46    75.5  437  1.118847e+12  16.657900   278.598900
     2005-06-15 14:49:47    85.5  437  1.118847e+12  16.130900   322.998400
     2005-06-15 14:49:48    95.5  437  1.118847e+12  16.430600   367.761600
     2005-06-15 14:49:49   105.5  437  1.118847e+12  17.410300   413.588400
     2005-06-15 14:49:50   115.5  437  1.118847e+12  18.355500   458.081900
     2005-06-15 14:49:51   125.5  437  1.118847e+12  17.591300   499.134600
     2005-06-15 14:49:52   135.5  437  1.118847e+12  17.668100   535.880900
     2005-06-15 14:49:53   145.5  437  1.118847e+12  18.431600   571.199700
     2005-06-15 14:49:54   155.5  437  1.118847e+12  18.072300   607.279700
     2005-06-15 14:49:55   165.5  437  1.118847e+12  17.601300   646.529900
     2005-06-15 14:49:56   175.5  437  1.118847e+12  17.327600   687.665400
     2005-06-15 14:49:57   185.5  437  1.118847e+12  17.056600   732.249800
     2005-06-15 14:49:58   195.5  437  1.118847e+12  16.456900   777.691900
     2005-06-15 14:49:59   205.5  437  1.118847e+12  12.999600   827.392800
     2005-06-15 14:50:00   215.5  437  1.118847e+12  11.227900   876.678400
     2005-06-15 14:50:01   225.5  437  1.118847e+12  11.653000   926.757400
     2005-06-15 14:50:02   235.5  437  1.118847e+12  11.286600   978.255700
     2005-06-15 14:50:03   245.5  437  1.118847e+12  10.747200  1034.549600
     2005-06-15 14:50:04   255.5  437  1.118847e+12  10.852600  1092.173700
     2005-06-15 14:50:05   265.5  437  1.118847e+12  10.917100  1147.714700
     2005-06-15 14:50:06   275.5  437  1.118847e+12   9.421900  1198.508000
     2005-06-15 14:50:07   285.5  437  1.118847e+12   7.389700  1246.675700
     2005-06-15 14:50:08   295.5  437  1.118847e+12   6.532700  1292.783100
     2005-06-15 14:50:09   305.5  437  1.118847e+12   7.086300  1334.235300
...                          ...  ...           ...        ...          ...
3109 2005-06-15 15:01:09  6905.5  510  1.118848e+12  49.965000   888.403500
     2005-06-15 15:01:10  6915.5  510  1.118848e+12  50.097200   919.969800
     2005-06-15 15:01:11  6925.5  510  1.118848e+12  50.344900   950.634800
     2005-06-15 15:01:12  6935.5  510  1.118848e+12  50.598900   983.280300
     2005-06-15 15:01:13  6945.5  510  1.118848e+12  50.866000  1017.322700
     2005-06-15 15:01:14  6955.5  510  1.118848e+12  52.012800  1053.410300
     2005-06-15 15:01:15  6965.5  510  1.118848e+12  52.337400  1089.725600
     2005-06-15 15:01:16  6975.5  510  1.118848e+12  52.399100  1127.495900
     2005-06-15 15:01:17  6985.5  510  1.118848e+12  52.437200  1166.052400
     2005-06-15 15:01:18  6995.5  510  1.118848e+12  52.392700  1203.944000
     2005-06-15 15:01:19  7005.5  510  1.118848e+12  52.860400  1245.317800
     2005-06-15 15:01:20  7015.5  510  1.118848e+12  53.701300  1294.186700
     2005-06-15 15:01:21  7025.5  510  1.118848e+12  53.600400  1343.669900
     2005-06-15 15:01:22  7035.5  510  1.118848e+12  53.584900  1390.746500
     2005-06-15 15:01:23  7045.5  510  1.118848e+12  53.590400  1436.208900
     2005-06-15 15:01:24  7055.5  510  1.118848e+12  52.816100  1483.174400
     2005-06-15 15:01:25  7065.5  510  1.118848e+12  52.487700  1528.895100
     2005-06-15 15:01:26  7075.5  510  1.118848e+12  52.267000  1573.851200
     2005-06-15 15:01:27  7085.5  510  1.118848e+12  52.124300  1617.437700
     2005-06-15 15:01:28  7095.5  510  1.118848e+12  51.994000  1659.106200
     2005-06-15 15:01:29  7105.5  510  1.118848e+12  52.304800  1701.418600
     2005-06-15 15:01:30  7115.5  510  1.118848e+12  53.673400  1745.842200
     2005-06-15 15:01:31  7125.5  510  1.118848e+12  54.282500  1792.645900
     2005-06-15 15:01:32  7135.5  510  1.118848e+12  54.286800  1842.750100
     2005-06-15 15:01:33  7145.5  510  1.118848e+12  55.083200  1894.847100
     2005-06-15 15:01:34  7155.5  510  1.118848e+12  56.154300  1944.137100
     2005-06-15 15:01:35  7165.5  510  1.118848e+12  57.547400  1991.812800
     2005-06-15 15:01:36  7175.5  510  1.118848e+12  57.577900  2040.323800
     2005-06-15 15:01:37  7185.5  510  1.118848e+12  57.414500  2089.593400
     2005-06-15 15:01:38  7191.5  510  1.118848e+12  57.405000  2120.135500

                                globalX         globalY  vLenght  vWidth  \
vID  dateTime
2    2005-06-15 14:49:40  6451147.05075  1873334.595875     14.5     4.9
     2005-06-15 14:49:41  6451171.07880  1873308.121600     14.5     4.9
     2005-06-15 14:49:42  6451196.26890  1873280.366000     14.5     4.9
     2005-06-15 14:49:43  6451221.32770  1873254.149300     14.5     4.9
     2005-06-15 14:49:44  6451249.44020  1873226.795300     14.5     4.9
     2005-06-15 14:49:45  6451276.55360  1873197.369400     14.5     4.9
     2005-06-15 14:49:46  6451305.62580  1873167.561400     14.5     4.9
     2005-06-15 14:49:47  6451337.91880  1873137.082800     14.5     4.9
     2005-06-15 14:49:48  6451370.43160  1873105.807000     14.5     4.9
     2005-06-15 14:49:49  6451403.48850  1873073.998600     14.5     4.9
     2005-06-15 14:49:50  6451435.56690  1873043.150300     14.5     4.9
     2005-06-15 14:49:51  6451466.48710  1873015.865700     14.5     4.9
     2005-06-15 14:49:52  6451493.86300  1872991.230200     14.5     4.9
     2005-06-15 14:49:53  6451519.68280  1872967.114800     14.5     4.9
     2005-06-15 14:49:54  6451546.81490  1872943.332100     14.5     4.9
     2005-06-15 14:49:55  6451576.56980  1872917.526900     14.5     4.9
     2005-06-15 14:49:56  6451607.68290  1872890.569600     14.5     4.9
     2005-06-15 14:49:57  6451641.36670  1872861.358500     14.5     4.9
     2005-06-15 14:49:58  6451675.89490  1872831.836900     14.5     4.9
     2005-06-15 14:49:59  6451715.50400  1872801.608200     14.5     4.9
     2005-06-15 14:50:00  6451753.67560  1872770.389600     14.5     4.9
     2005-06-15 14:50:01  6451791.11830  1872737.034000     14.5     4.9
     2005-06-15 14:50:02  6451830.21380  1872703.530700     14.5     4.9
     2005-06-15 14:50:03  6451873.03330  1872666.971500     14.5     4.9
     2005-06-15 14:50:04  6451916.41590  1872629.039300     14.5     4.9
     2005-06-15 14:50:05  6451958.25300  1872592.503000     14.5     4.9
     2005-06-15 14:50:06  6451997.43920  1872560.216400     14.5     4.9
     2005-06-15 14:50:07  6452035.00780  1872529.999700     14.5     4.9
     2005-06-15 14:50:08  6452070.27370  1872500.239700     14.5     4.9
     2005-06-15 14:50:09  6452101.14070  1872472.575300     14.5     4.9
...                                 ...             ...      ...     ...
3109 2005-06-15 15:01:09  6451736.90280  1872733.552300     14.0     5.9
     2005-06-15 15:01:10  6451760.75510  1872712.487300     14.0     5.9
     2005-06-15 15:01:11  6451783.75870  1872692.161600     14.0     5.9
     2005-06-15 15:01:12  6451808.22210  1872670.559400     14.0     5.9
     2005-06-15 15:01:13  6451833.69170  1872648.036800     14.0     5.9
     2005-06-15 15:01:14  6451860.14870  1872623.468100     14.0     5.9
     2005-06-15 15:01:15  6451887.31780  1872599.369300     14.0     5.9
     2005-06-15 15:01:16  6451915.75410  1872574.515800     14.0     5.9
     2005-06-15 15:01:17  6451944.72620  1872549.200600     14.0     5.9
     2005-06-15 15:01:18  6451973.20810  1872524.315700     14.0     5.9
     2005-06-15 15:01:19  6452003.99960  1872496.713200     14.0     5.9
     2005-06-15 15:01:20  6452040.24830  1872463.838800     14.0     5.9
     2005-06-15 15:01:21  6452077.72920  1872431.288800     14.0     5.9
     2005-06-15 15:01:22  6452113.25010  1872400.401600     14.0     5.9
     2005-06-15 15:01:23  6452147.32030  1872370.650800     14.0     5.9
     2005-06-15 15:01:24  6452183.06460  1872340.252700     14.0     5.9
     2005-06-15 15:01:25  6452217.63870  1872310.283900     14.0     5.9
     2005-06-15 15:01:26  6452251.92580  1872280.674500     14.0     5.9
     2005-06-15 15:01:27  6452284.94910  1872252.238300     14.0     5.9
     2005-06-15 15:01:28  6452315.98350  1872225.315800     14.0     5.9
     2005-06-15 15:01:29  6452347.14940  1872197.036700     14.0     5.9
     2005-06-15 15:01:30  6452380.39550  1872166.033800     14.0     5.9
     2005-06-15 15:01:31  6452415.38420  1872135.121500     14.0     5.9
     2005-06-15 15:01:32  6452453.03710  1872102.392900     14.0     5.9
     2005-06-15 15:01:33  6452492.21000  1872067.357800     14.0     5.9
     2005-06-15 15:01:34  6452529.27700  1872034.430900     14.0     5.9
     2005-06-15 15:01:35  6452565.62420  1872002.176900     14.0     5.9
     2005-06-15 15:01:36  6452603.40940  1871971.312000     14.0     5.9
     2005-06-15 15:01:37  6452642.39610  1871940.193300     14.0     5.9
     2005-06-15 15:01:38  6452666.26100  1871921.199500     14.0     5.9

                          vType    veloc    accel  line    pred    foll  \
vID  dateTime
2    2005-06-15 14:49:40      2  40.0025  0.03125   2.0     0.0     0.0
     2005-06-15 14:49:41      2  39.0260 -1.85300   2.0     0.0    11.7
     2005-06-15 14:49:42      2  35.4440 -2.79500   2.0     0.0    13.0
     2005-06-15 14:49:43      2  38.1130  4.21500   2.0     0.0    13.0
     2005-06-15 14:49:44      2  39.4610  0.59800   2.0     0.0    13.0
     2005-06-15 14:49:45      2  39.8820  0.20500   2.0     0.0    13.0
     2005-06-15 14:49:46      2  43.2380  3.94300   2.0     0.0    13.0
     2005-06-15 14:49:47      2  44.8580 -0.37600   2.0     0.0    13.0
     2005-06-15 14:49:48      2  45.4040  2.91600   2.0     0.0    13.0
     2005-06-15 14:49:49      2  45.2830 -1.97200   2.0     0.0    13.0
     2005-06-15 14:49:50      2  42.8700 -4.14000   2.0     0.0    13.0
     2005-06-15 14:49:51      2  39.4340 -4.55300   2.0     0.0    13.0
     2005-06-15 14:49:52      2  35.0050  0.26700   2.0     0.0    13.0
     2005-06-15 14:49:53      2  35.5100 -0.44600   2.0     0.0    13.0
     2005-06-15 14:49:54      2  37.7340  4.91800   2.0     0.0    13.0
     2005-06-15 14:49:55      2  39.8910  0.67000   2.0     0.0    13.0
     2005-06-15 14:49:56      2  43.2090  4.44000   2.0     0.0    13.0
     2005-06-15 14:49:57      2  45.0000  0.00000   2.0     0.0    13.0
     2005-06-15 14:49:58      2  47.3600  6.27500   2.0     0.0    13.0
     2005-06-15 14:49:59      2  49.5740 -4.00800   1.6     0.0    11.8
     2005-06-15 14:50:00      2  50.1240  1.66300   1.0     0.0    10.0
     2005-06-15 14:50:01      2  50.0240  1.10400   1.0     0.0    10.0
     2005-06-15 14:50:02      2  53.9120  6.47400   1.0     0.0    10.0
     2005-06-15 14:50:03      2  57.4660  0.42600   1.0     0.0    10.0
     2005-06-15 14:50:04      2  57.2380 -3.70400   1.0     0.0    10.0
     2005-06-15 14:50:05      2  53.3980 -5.01800   1.0     0.0    10.0
     2005-06-15 14:50:06      2  49.1990 -1.01400   1.0     0.0    10.0
     2005-06-15 14:50:07      2  47.2420 -0.03500   1.0     0.0    10.0
     2005-06-15 14:50:08      2  43.4340 -4.88900   1.0     0.0    10.0
     2005-06-15 14:50:09      2  40.6790 -1.01400   1.0     0.0    10.0
...                         ...      ...      ...   ...     ...     ...
3109 2005-06-15 15:01:09      2  34.1310 -4.18700   5.0  2311.0  2325.0
     2005-06-15 15:01:10      2  29.8300 -0.09200   5.0  2311.0  2325.0
     2005-06-15 15:01:11      2  32.1000  2.04000   5.0  2311.0  2325.0
     2005-06-15 15:01:12      2  32.8670  2.62200   5.0  2311.0  2325.0
     2005-06-15 15:01:13      2  35.2980  1.57400   5.0  2311.0  2325.0
     2005-06-15 15:01:14      2  36.2320 -0.85000   5.0  2311.0  2325.0
     2005-06-15 15:01:15      2  36.9980  2.58300   5.0  2311.0  2325.0
     2005-06-15 15:01:16      2  38.2040  0.78900   5.0  2311.0  2325.0
     2005-06-15 15:01:17      2  38.4870 -1.95800   5.0  2311.0  2325.0
     2005-06-15 15:01:18      2  38.1670  2.93400   5.0  2311.0  2325.0
     2005-06-15 15:01:19      2  45.7870  5.21900   5.0  2311.0  2325.0
     2005-06-15 15:01:20      2  50.5310  1.83700   5.0  2311.0  2325.0
     2005-06-15 15:01:21      2  47.7830 -2.71600   5.0  2311.0  2325.0
     2005-06-15 15:01:22      2  46.1320 -1.90600   5.0  2311.0  2325.0
     2005-06-15 15:01:23      2  45.6390  2.64700   5.0  2311.0  2325.0
     2005-06-15 15:01:24      2  47.6030 -2.62900   5.0  2311.0  2325.0
     2005-06-15 15:01:25      2  44.2770 -0.75700   5.0  2311.0  2325.0
     2005-06-15 15:01:26      2  45.1190 -1.93700   5.0  2311.0  2325.0
     2005-06-15 15:01:27      2  42.3440 -1.95700   5.0  2311.0  2325.0
     2005-06-15 15:01:28      2  40.8850  0.53700   5.0  2311.0  2325.0
     2005-06-15 15:01:29      2  44.2220  0.80600   5.0  2311.0  2325.0
     2005-06-15 15:01:30      2  44.9500  2.93900   5.0  2311.0  2325.0
     2005-06-15 15:01:31      2  49.1280  4.05300   5.0  2311.0  2325.0
     2005-06-15 15:01:32      2  50.7730  3.94100   5.0  2311.0  2325.0
     2005-06-15 15:01:33      2  51.6420 -5.40400   5.0  2311.0  2325.0
     2005-06-15 15:01:34      2  48.2410 -0.58000   5.0  2311.0  2325.0
     2005-06-15 15:01:35      2  47.5150  0.81000   5.0  1617.7  2325.0
     2005-06-15 15:01:36      2  48.8950 -0.17300   5.0     0.0  2325.0
     2005-06-15 15:01:37      2  50.0930  3.07100   5.0     0.0  2325.0
     2005-06-15 15:01:38      2  51.0300  0.00000   5.0     0.0  2325.0

                             spac  headway
vID  dateTime
2    2005-06-15 14:49:40    0.000    0.000
     2005-06-15 14:49:41    0.000    0.000
     2005-06-15 14:49:42    0.000    0.000
     2005-06-15 14:49:43    0.000    0.000
     2005-06-15 14:49:44    0.000    0.000
     2005-06-15 14:49:45    0.000    0.000
     2005-06-15 14:49:46    0.000    0.000
     2005-06-15 14:49:47    0.000    0.000
     2005-06-15 14:49:48    0.000    0.000
     2005-06-15 14:49:49    0.000    0.000
     2005-06-15 14:49:50    0.000    0.000
     2005-06-15 14:49:51    0.000    0.000
     2005-06-15 14:49:52    0.000    0.000
     2005-06-15 14:49:53    0.000    0.000
     2005-06-15 14:49:54    0.000    0.000
     2005-06-15 14:49:55    0.000    0.000
     2005-06-15 14:49:56    0.000    0.000
     2005-06-15 14:49:57    0.000    0.000
     2005-06-15 14:49:58    0.000    0.000
     2005-06-15 14:49:59    0.000    0.000
     2005-06-15 14:50:00    0.000    0.000
     2005-06-15 14:50:01    0.000    0.000
     2005-06-15 14:50:02    0.000    0.000
     2005-06-15 14:50:03    0.000    0.000
     2005-06-15 14:50:04    0.000    0.000
     2005-06-15 14:50:05    0.000    0.000
     2005-06-15 14:50:06    0.000    0.000
     2005-06-15 14:50:07    0.000    0.000
     2005-06-15 14:50:08    0.000    0.000
     2005-06-15 14:50:09    0.000    0.000
...                           ...      ...
3109 2005-06-15 15:01:09   79.454    2.330
     2005-06-15 15:01:10   80.560    2.700
     2005-06-15 15:01:11   84.541    2.637
     2005-06-15 15:01:12   89.826    2.733
     2005-06-15 15:01:13   95.715    2.711
     2005-06-15 15:01:14  103.587    2.860
     2005-06-15 15:01:15  108.337    2.929
     2005-06-15 15:01:16  113.285    2.966
     2005-06-15 15:01:17  121.125    3.149
     2005-06-15 15:01:18  129.573    3.393
     2005-06-15 15:01:19  136.368    2.993
     2005-06-15 15:01:20  132.987    2.633
     2005-06-15 15:01:21  126.986    2.658
     2005-06-15 15:01:22  122.004    2.647
     2005-06-15 15:01:23  120.312    2.637
     2005-06-15 15:01:24  119.083    2.502
     2005-06-15 15:01:25  118.737    2.680
     2005-06-15 15:01:26  119.006    2.640
     2005-06-15 15:01:27  119.345    2.820
     2005-06-15 15:01:28  123.311    3.019
     2005-06-15 15:01:29  131.022    2.966
     2005-06-15 15:01:30  135.906    3.027
     2005-06-15 15:01:31  127.182    2.594
     2005-06-15 15:01:32  125.474    2.473
     2005-06-15 15:01:33  122.174    2.368
     2005-06-15 15:01:34  122.702    2.545
     2005-06-15 15:01:35   87.145    1.852
     2005-06-15 15:01:36    0.000    0.000
     2005-06-15 15:01:37    0.000    0.000
     2005-06-15 15:01:38    0.000    0.000

[120032 rows x 17 columns]

In [17]:
num_v = data.groupby(['vID']).size()

In [18]:
num_v #foe vID how many times it appears

vID
2       437
4       351
5       452
6       357
8       448
9       409
10      436
12      443
13      432
14      515
18      291
20      414
21      439
22      441
23      438
25      436
26      438
27      432
31      465
32      438
33      383
34      451
35      280
37      408
39      450
40      391
42      389
43      458
44      379
47      428
       ...
3004    725
3005    726
3006    741
3007    853
3008    724
3009    732
3011    842
3014    676
3015    578
3018    714
3019    704
3021    678
3022    641
3023    403
3024    834
3025    644
3026    326
3030    667
3032    820
3033    633
3034    567
3101    255
3102    443
3103    461
3104    474
3105    534
3106    515
3107    282
3108    359
3109    510
dtype: int64

In [19]:
num_v.count() #num of different vehicles

2169

In [20]:
data.describe()

,vID,frID,tFr,Timestamp,localX,localY,globalX,globalY,vLenght,vWidth,vType,veloc,accel,line,pred,foll,spac,headway
count,1180598.000000,1180598.000000,1180598.00000,1.180598e+06,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000,1180598.000000
mean,1687.341261,4972.144159,585.54170,1.118847e+12,29.518502,983.008826,6451824.104109,1872689.857423,14.751878,6.145379,2.009898,37.496414,0.329052,2.965503,1603.584081,1610.456129,76.861747,166.340722
std,862.738747,2631.668242,160.25284,2.631668e+05,16.661830,594.629100,444.974278,395.885228,5.116659,1.027755,0.187414,14.875941,5.045285,1.468343,916.397282,916.845336,48.542040,1269.461537
min,2.000000,8.000000,177.00000,1.118847e+12,0.510000,0.000000,6451106.650000,1871874.940000,4.000000,2.000000,1.000000,0.000000,-11.200000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1023.000000,2705.000000,470.00000,1.118847e+12,17.338000,471.095500,6451438.148000,1872368.351500,12.500000,5.400000,2.000000,29.900000,-1.480000,2.000000,890.000000,898.000000,48.480000,1.490000
50%,1720.000000,5074.000000,541.00000,1.118847e+12,29.645000,932.115000,6451783.694000,1872720.025000,14.500000,6.000000,2.000000,39.250000,0.000000,3.000000,1657.000000,1662.000000,67.730000,2.020000
75%,2490.000000,7387.000000,687.00000,1.118848e+12,41.906000,1466.302250,6452185.333750,1873026.788750,16.500000,6.900000,2.000000,47.370000,2.380000,4.000000,2458.000000,2467.000000,95.780000,2.830000
max,3109.000000,9536.000000,1010.00000,1.118848e+12,73.475000,2195.462000,6452734.058000,1873372.900000,76.100000,8.500000,3.000000,95.300000,11.200000,8.000000,3109.000000,3109.000000,777.730000,9999.990000

In [21]:
v_dt.groupby(['dateTime'])

In [22]:
v_ts_gr.mean()

123.89526707944171