In [42]:
#%matplotlib inline

from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import csv
import matplotlib as plt

In [43]:
c_names = ['vID', 'frID', 'tFr','Timestamp', 'localX', 'localY', 'globalX','globalY', 'vLenght', 'vWidth', 'vType', 
           'veloc','accel', 'line', 'pred', 'foll', 'spac', 'headway', 'dateTime']

In [44]:
data = pd.read_table('D:\\zzzLola\\PhD\\DataSet\\US101\\test\\portion1Set2DT.txt', sep='\t', header=None, names=c_names)

In [45]:
data[:50]

,vID,frID,tFr,Timestamp,localX,localY,globalX,globalY,vLenght,vWidth,vType,veloc,accel,line,pred,foll,spac,headway,dateTime
0,2,13,437,1118846980200,16.467,35.381,6451137.641,1873344.962,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
1,2,14,437,1118846980300,16.447,39.381,6451140.329,1873342.000,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
2,2,15,437,1118846980400,16.426,43.381,6451143.018,1873339.038,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
3,2,16,437,1118846980500,16.405,47.380,6451145.706,1873336.077,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
4,2,17,437,1118846980600,16.385,51.381,6451148.395,1873333.115,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
5,2,18,437,1118846980700,16.364,55.381,6451151.084,1873330.153,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
6,2,19,437,1118846980800,16.344,59.381,6451153.772,1873327.192,14.5,4.9,2,40.00,0.00,2,0,0,0,0,2005-06-15 14:49:40
7,2,20,437,1118846980900,16.323,63.379,6451156.461,1873324.230,14.5,4.9,2,40.02,0.25,2,0,0,0,0,2005-06-15 14:49:40
8,2,21,437,1118846981000,16.303,67.383,6451159.149,1873321.268,14.5,4.9,2,40.03,0.13,2,0,0,0,0,2005-06-15 14:49:41
9,2,22,437,1118846981100,16.282,71.398,6451161.838,1873318.307,14.5,4.9,2,39.93,-1.63,2,0,13,0,0,2005-06-15 14:49:41
10,2,23,437,1118846981200,16.262,75.401,6451164.546,1873315.323,14.5,4.9,2,39.61,-4.54,2,0,13,0,0,2005-06-15 14:49:41
11,2,24,437,1118846981300,16.254,79.349,6451167.199,1873312.382,14.5,4.9,2,39.14,-5.73,2,0,13,0,0,2005-06-15 14:49:41
12,2,25,437,1118846981400,16.221,83.233,6451169.802,1873309.533,14.5,4.9,2,38.61,-5.15,2,0,13,0,0,2005-06-15 14:49:41
13,2,26,437,1118846981500,16.201,87.043,6451172.358,1873306.719,14.5,4.9,2,38.28,-1.61,2,0,13,0,0,2005-06-15 14:49:41
14,2,27,437,1118846981600,16.169,90.829,6451174.961,1873303.870,14.5,4.9,2,38.42,3.73,2,0,13,0,0,2005-06-15 14:49:41
15,2,28,437,1118846981700,16.204,94.683,6451177.613,1873300.929,14.5,4.9,2,38.78,4.86,2,0,13,0,0,2005-06-15 14:49:41
16,2,29,437,1118846981800,16.252,98.611,6451180.342,1873297.924,14.5,4.9,2,38.92,0.00,2,0,13,0,0,2005-06-15 14:49:41
17,2,30,437,1118846981900,16.339,102.560,6451182.980,1873294.961,14.5,4.9,2,38.54,-8.59,2,0,13,0,0,2005-06-15 14:49:41
18,2,31,437,1118846982000,16.400,106.385,6451185.537,1873292.122,14.5,4.9,2,37.51,-11.20,2,0,13,0,0,2005-06-15 14:49:42
19,2,32,437,1118846982100,16.430,110.079,6451188.021,1873289.408,14.5,4.9,2,36.34,-10.86,2,0,13,0,0,2005-06-15 14:49:42
20,2,33,437,1118846982200,16.435,113.628,6451190.424,1873286.817,14.5,4.9,2,35.50,-6.20,2,0,13,0,0,2005-06-15 14:49:42
21,2,34,437,1118846982300,16.478,117.118,6451192.757,1873284.247,14.5,4.9,2,35.08,-1.89,2,0,13,0,0,2005-06-15 14:49:42
22,2,35,437,1118846982400,16.520,120.600,6451195.109,1873281.656,14.5,4.9,2,34.96,0.18,2,0,13,0,0,2005-06-15 14:49:42
23,2,36,437,1118846982500,16.562,124.096,6451197.462,1873279.065,14.5,4.9,2,34.98,0.25,2,0,13,0,0,2005-06-15 14:49:42
24,2,37,437,1118846982600,16.605,127.597,6451199.814,1873276.473,14.5,4.9,2,35.00,0.04,2,0,13,0,0,2005-06-15 14:49:42
25,2,38,437,1118846982700,16.647,131.099,6451202.167,1873273.882,14.5,4.9,2,34.99,-0.20,2,0,13,0,0,2005-06-15 14:49:42
26,2,39,437,1118846982800,16.691,134.595,6451204.519,1873271.290,14.5,4.9,2,34.98,-0.02,2,0,13,0,0,2005-06-15 14:49:42
27,2,40,437,1118846982900,16.727,138.081,6451206.879,1873268.700,14.5,4.9,2,35.10,1.95,2,0,13,0,0,2005-06-15 14:49:42
28,2,41,437,1118846983000,16.796,141.578,6451209.191,1873266.113,14.5,4.9,2,35.49,5.55,2,0,13,0,0,2005-06-15 14:49:43
29,2,42,437,1118846983100,16.795,145.131,6451211.610,1873263.514,14.5,4.9,2,36.20,8.99,2,0,13,0,0,2005-06-15 14:49:43
30,2,43,437,1118846983200,16.724,148.784,6451214.156,1873260.882,14.5,4.9,2,37.15,10.44,2,0,13,0,0,2005-06-15 14:49:43
31,2,44,437,1118846983300,16.588,152.559,6451216.824,1873258.213,14.5,4.9,2,38.12,9.30,2,0,13,0,0,2005-06-15 14:49:43
32,2,45,437,1118846983400,16.376,156.449,6451219.616,1873255.522,14.5,4.9,2,38.76,4.36,2,0,13,0,0,2005-06-15 14:49:43
33,2,46,437,1118846983500,16.064,160.379,6451222.548,1873252.829,14.5,4.9,2,38.95,-0.73,2,0,13,0,0,2005-06-15 14:49:43
34,2,47,437,1118846983600,15.763,164.277,6451225.462,1873250.139,14.5,4.9,2,38.95,-1.15,2,0,13,0,0,2005-06-15 14:49:43
35,2,48,437,1118846983700,15.471,168.150,6451228.376,1873247.450,14.5,4.9,2,38.99,1.90,2,0,13,0,0,2005-06-15 14:49:43
36,2,49,437,1118846983800,15.226,172.044,6451231.290,1873244.760,14.5,4.9,2,39.18,3.47,2,0,13,0,0,2005-06-15 14:49:43
37,2,50,437,1118846983900,14.979,176.000,6451234.204,1873242.071,14.5,4.9,2,39.34,0.02,2,0,13,0,0,2005-06-15 14:49:43
38,2,51,437,1118846984000,14.720,179.959,6451237.144,1873239.374,14.5,4.9,2,39.20,-3.52,2,0,13,0,0,2005-06-15 14:49:44
39,2,52,437,1118846984100,14.508,183.862,6451239.988,1873236.708,14.5,4.9,2,38.89,-3.28,2,0,13,0,0,2005-06-15 14:49:44
40,2,53,437,1118846984200,14.331,187.716,6451242.770,1873234.057,14.5,4.9,2,38.73,-0.33,2,0,13,0,0,2005-06-15 14:49:44
41,2,54,437,1118846984300,14.240,191.561,6451245.501,1873231.336,14.5,4.9,2,38.88,3.49,2,0,13,0,0,2005-06-15 14:49:44
42,2,55,437,1118846984400,14.309,195.455,6451248.125,1873228.494,14.5,4.9,2,39.28,5.00,2,0,13,0,0,2005-06-15 14:49:44
43,2,56,437,1118846984500,14.428,199.414,6451250.788,1873225.539,14.5,4.9,2,39.68,3.76,2,0,13,0,0,2005-06-15 14:49:44
44,2,57,437,1118846984600,14.540,203.417,6451253.489,1873222.554,14.5,4.9,2,39.94,1.29,2,0,13,0,0,2005-06-15 14:49:44
45,2,58,437,1118846984700,14.646,207.430,6451256.177,1873219.592,14.5,4.9,2,40.02,-0.22,2,0,13,0,0,2005-06-15 14:49:44
46,2,59,437,1118846984800,14.751,211.431,6451258.866,1873216.630,14.5,4.9,2,40.00,-0.21,2,0,13,0,0,2005-06-15 14:49:44
47,2,60,437,1118846984900,14.856,215.428,6451261.554,1873213.669,14.5,4.9,2,39.99,0.00,2,0,13,0,0,2005-06-15 14:49:44
48,2,61,437,1118846985000,14.962,219.427,6451264.243,1873210.707,14.5,4.9,2,39.99,0.00,2,0,13,0,0,2005-06-15 14:49:45
49,2,62,437,1118846985100,15.067,223.462,6451266.932,1873207.745,14.5,4.9,2,39.65,-5.35,2,0,13,0,0,2005-06-15 14:49:45

In [46]:
v_ts = DataFrame(data, columns=['vID', 'Timestamp'])

In [47]:
v_dt = DataFrame(data, columns=['vID', 'dateTime'])

In [48]:
v_ts[:10]

   vID      Timestamp
0    2  1118846980200
1    2  1118846980300
2    2  1118846980400
3    2  1118846980500
4    2  1118846980600
5    2  1118846980700
6    2  1118846980800
7    2  1118846980900
8    2  1118846981000
9    2  1118846981100

In [49]:
v_dt[:10]

   vID             dateTime
0    2  2005-06-15 14:49:40
1    2  2005-06-15 14:49:40
2    2  2005-06-15 14:49:40
3    2  2005-06-15 14:49:40
4    2  2005-06-15 14:49:40
5    2  2005-06-15 14:49:40
6    2  2005-06-15 14:49:40
7    2  2005-06-15 14:49:40
8    2  2005-06-15 14:49:41
9    2  2005-06-15 14:49:41

In [50]:
v_ts_gr = v_ts.groupby(['Timestamp']).size()
v_ts_gr

Timestamp
1118846979700    1
1118846979800    1
1118846979900    1
1118846980000    1
1118846980100    1
1118846980200    2
1118846980300    2
1118846980400    2
1118846980500    2
1118846980600    2
1118846980700    2
1118846980800    2
1118846980900    2
1118846981000    2
1118846981100    2
1118846981200    2
1118846981300    2
1118846981400    2
1118846981500    2
1118846981600    2
1118846981700    2
1118846981800    2
1118846981900    2
1118846982000    2
1118846982100    2
1118846982200    2
1118846982300    2
1118846982400    2
1118846982500    2
1118846982600    2
                ..
1118847025700    2
1118847025800    2
1118847025900    2
1118847026000    2
1118847026100    2
1118847026200    2
1118847026300    2
1118847026400    2
1118847026500    2
1118847026600    2
1118847026700    2
1118847026800    1
1118847026900    1
1118847027000    1
1118847027100    1
1118847027200    1
1118847027300    1
1118847027400    1
1118847027500    1
1118847027600    1
1118847027700    1
1118847027800    1
1118847027900    1
1118847028000    1
1118847028100    1
1118847028200    1
1118847028300    1
1118847028400    1
1118847028500    1
1118847028600    1
dtype: int64

In [51]:
v_ts_gr.max()

4

In [52]:
v_ts_gr.min()

1

In [53]:
v_dt_gr = v_dt.groupby(['dateTime']).size()
v_dt_gr

dateTime
2005-06-15 14:49:39     3
2005-06-15 14:49:40    18
2005-06-15 14:49:41    20
2005-06-15 14:49:42    20
2005-06-15 14:49:43    20
2005-06-15 14:49:44    20
2005-06-15 14:49:45    20
2005-06-15 14:49:46    20
2005-06-15 14:49:47    20
2005-06-15 14:49:48    20
2005-06-15 14:49:49    20
2005-06-15 14:49:50    20
2005-06-15 14:49:51    23
2005-06-15 14:49:52    30
2005-06-15 14:49:53    40
2005-06-15 14:49:54    40
2005-06-15 14:49:55    40
2005-06-15 14:49:56    40
2005-06-15 14:49:57    40
2005-06-15 14:49:58    40
2005-06-15 14:49:59    40
2005-06-15 14:50:00    40
2005-06-15 14:50:01    40
2005-06-15 14:50:02    40
2005-06-15 14:50:03    40
2005-06-15 14:50:04    40
2005-06-15 14:50:05    40
2005-06-15 14:50:06    40
2005-06-15 14:50:07    40
2005-06-15 14:50:08    40
2005-06-15 14:50:09    40
2005-06-15 14:50:10    40
2005-06-15 14:50:11    40
2005-06-15 14:50:12    40
2005-06-15 14:50:13    40
2005-06-15 14:50:14    40
2005-06-15 14:50:15    40
2005-06-15 14:50:16    40
2005-06-15 14:50:17    40
2005-06-15 14:50:18    40
2005-06-15 14:50:19    40
2005-06-15 14:50:20    40
2005-06-15 14:50:21    40
2005-06-15 14:50:22    40
2005-06-15 14:50:23    39
2005-06-15 14:50:24    29
2005-06-15 14:50:25    20
2005-06-15 14:50:26    18
2005-06-15 14:50:27    10
2005-06-15 14:50:28     7
dtype: int64

In [54]:
v_dt_gr.max()

40

In [55]:
v_dt_gr.min()

3

In [56]:
data_mean = data.groupby(['vID', 'dateTime']).mean()

In [57]:
data_mean #Mean values for the data grouped by vID and dateTime

                          frID  tFr     Timestamp     localX       localY  \
vID dateTime
2   2005-06-15 14:49:40   16.5  437  1.118847e+12  16.395125    49.380625
    2005-06-15 14:49:41   25.5  437  1.118847e+12  16.248700    85.049000
    2005-06-15 14:49:42   35.5  437  1.118847e+12  16.549500   122.327800
    2005-06-15 14:49:43   45.5  437  1.118847e+12  16.078200   158.535100
    2005-06-15 14:49:44   55.5  437  1.118847e+12  14.532900   197.567300
    2005-06-15 14:49:45   65.5  437  1.118847e+12  15.562200   237.208600
    2005-06-15 14:49:46   75.5  437  1.118847e+12  16.657900   278.598900
    2005-06-15 14:49:47   85.5  437  1.118847e+12  16.130900   322.998400
    2005-06-15 14:49:48   95.5  437  1.118847e+12  16.430600   367.761600
    2005-06-15 14:49:49  105.5  437  1.118847e+12  17.410300   413.588400
    2005-06-15 14:49:50  115.5  437  1.118847e+12  18.355500   458.081900
    2005-06-15 14:49:51  125.5  437  1.118847e+12  17.591300   499.134600
    2005-06-15 14:49:52  135.5  437  1.118847e+12  17.668100   535.880900
    2005-06-15 14:49:53  145.5  437  1.118847e+12  18.431600   571.199700
    2005-06-15 14:49:54  155.5  437  1.118847e+12  18.072300   607.279700
    2005-06-15 14:49:55  165.5  437  1.118847e+12  17.601300   646.529900
    2005-06-15 14:49:56  175.5  437  1.118847e+12  17.327600   687.665400
    2005-06-15 14:49:57  185.5  437  1.118847e+12  17.056600   732.249800
    2005-06-15 14:49:58  195.5  437  1.118847e+12  16.456900   777.691900
    2005-06-15 14:49:59  205.5  437  1.118847e+12  12.999600   827.392800
    2005-06-15 14:50:00  215.5  437  1.118847e+12  11.227900   876.678400
    2005-06-15 14:50:01  225.5  437  1.118847e+12  11.653000   926.757400
    2005-06-15 14:50:02  235.5  437  1.118847e+12  11.286600   978.255700
    2005-06-15 14:50:03  245.5  437  1.118847e+12  10.747200  1034.549600
    2005-06-15 14:50:04  255.5  437  1.118847e+12  10.852600  1092.173700
    2005-06-15 14:50:05  265.5  437  1.118847e+12  10.917100  1147.714700
    2005-06-15 14:50:06  275.5  437  1.118847e+12   9.421900  1198.508000
    2005-06-15 14:50:07  285.5  437  1.118847e+12   7.389700  1246.675700
    2005-06-15 14:50:08  295.5  437  1.118847e+12   6.532700  1292.783100
    2005-06-15 14:50:09  305.5  437  1.118847e+12   7.086300  1334.235300
...                        ...  ...           ...        ...          ...
6   2005-06-15 14:49:59  205.5  357  1.118847e+12  60.513200   777.939700
    2005-06-15 14:50:00  215.5  357  1.118847e+12  58.874100   821.153600
    2005-06-15 14:50:01  225.5  357  1.118847e+12  57.563100   862.637900
    2005-06-15 14:50:02  235.5  357  1.118847e+12  56.480500   903.853500
    2005-06-15 14:50:03  245.5  357  1.118847e+12  55.872400   943.986400
    2005-06-15 14:50:04  255.5  357  1.118847e+12  55.715400   985.958300
    2005-06-15 14:50:05  265.5  357  1.118847e+12  55.637200  1028.288200
    2005-06-15 14:50:06  275.5  357  1.118847e+12  55.248700  1069.928900
    2005-06-15 14:50:07  285.5  357  1.118847e+12  54.545200  1111.026700
    2005-06-15 14:50:08  295.5  357  1.118847e+12  54.876400  1153.791000
    2005-06-15 14:50:09  305.5  357  1.118847e+12  54.569000  1196.751600
    2005-06-15 14:50:10  315.5  357  1.118847e+12  54.747300  1240.391200
    2005-06-15 14:50:11  325.5  357  1.118847e+12  55.769200  1286.133500
    2005-06-15 14:50:12  335.5  357  1.118847e+12  55.889600  1330.994600
    2005-06-15 14:50:13  345.5  357  1.118847e+12  56.038600  1375.986300
    2005-06-15 14:50:14  355.5  357  1.118847e+12  56.309800  1422.056000
    2005-06-15 14:50:15  365.5  357  1.118847e+12  56.590300  1471.490000
    2005-06-15 14:50:16  375.5  357  1.118847e+12  55.896100  1519.680400
    2005-06-15 14:50:17  385.5  357  1.118847e+12  55.658900  1567.237500
    2005-06-15 14:50:18  395.5  357  1.118847e+12  55.151300  1616.241500
    2005-06-15 14:50:19  405.5  357  1.118847e+12  54.399400  1665.899000
    2005-06-15 14:50:20  415.5  357  1.118847e+12  53.987300  1715.876600
    2005-06-15 14:50:21  425.5  357  1.118847e+12  54.792600  1765.726300
    2005-06-15 14:50:22  435.5  357  1.118847e+12  55.325800  1817.404600
    2005-06-15 14:50:23  445.5  357  1.118847e+12  55.419000  1872.069200
    2005-06-15 14:50:24  455.5  357  1.118847e+12  56.863900  1928.320000
    2005-06-15 14:50:25  465.5  357  1.118847e+12  56.953100  1983.358600
    2005-06-15 14:50:26  475.5  357  1.118847e+12  58.597600  2040.118800
    2005-06-15 14:50:27  485.5  357  1.118847e+12  58.766600  2095.723300
    2005-06-15 14:50:28  494.0  357  1.118847e+12  58.119143  2144.347000

                                globalX         globalY  vLenght  vWidth  \
vID dateTime
2   2005-06-15 14:49:40  6451147.050750  1873334.595875     14.5     4.9
    2005-06-15 14:49:41  6451171.078800  1873308.121600     14.5     4.9
    2005-06-15 14:49:42  6451196.268900  1873280.366000     14.5     4.9
    2005-06-15 14:49:43  6451221.327700  1873254.149300     14.5     4.9
    2005-06-15 14:49:44  6451249.440200  1873226.795300     14.5     4.9
    2005-06-15 14:49:45  6451276.553600  1873197.369400     14.5     4.9
    2005-06-15 14:49:46  6451305.625800  1873167.561400     14.5     4.9
    2005-06-15 14:49:47  6451337.918800  1873137.082800     14.5     4.9
    2005-06-15 14:49:48  6451370.431600  1873105.807000     14.5     4.9
    2005-06-15 14:49:49  6451403.488500  1873073.998600     14.5     4.9
    2005-06-15 14:49:50  6451435.566900  1873043.150300     14.5     4.9
    2005-06-15 14:49:51  6451466.487100  1873015.865700     14.5     4.9
    2005-06-15 14:49:52  6451493.863000  1872991.230200     14.5     4.9
    2005-06-15 14:49:53  6451519.682800  1872967.114800     14.5     4.9
    2005-06-15 14:49:54  6451546.814900  1872943.332100     14.5     4.9
    2005-06-15 14:49:55  6451576.569800  1872917.526900     14.5     4.9
    2005-06-15 14:49:56  6451607.682900  1872890.569600     14.5     4.9
    2005-06-15 14:49:57  6451641.366700  1872861.358500     14.5     4.9
    2005-06-15 14:49:58  6451675.894900  1872831.836900     14.5     4.9
    2005-06-15 14:49:59  6451715.504000  1872801.608200     14.5     4.9
    2005-06-15 14:50:00  6451753.675600  1872770.389600     14.5     4.9
    2005-06-15 14:50:01  6451791.118300  1872737.034000     14.5     4.9
    2005-06-15 14:50:02  6451830.213800  1872703.530700     14.5     4.9
    2005-06-15 14:50:03  6451873.033300  1872666.971500     14.5     4.9
    2005-06-15 14:50:04  6451916.415900  1872629.039300     14.5     4.9
    2005-06-15 14:50:05  6451958.253000  1872592.503000     14.5     4.9
    2005-06-15 14:50:06  6451997.439200  1872560.216400     14.5     4.9
    2005-06-15 14:50:07  6452035.007800  1872529.999700     14.5     4.9
    2005-06-15 14:50:08  6452070.273700  1872500.239700     14.5     4.9
    2005-06-15 14:50:09  6452101.140700  1872472.575300     14.5     4.9
...                                 ...             ...      ...     ...
6   2005-06-15 14:49:59  6451647.011100  1872798.569800     14.0     4.9
    2005-06-15 14:50:00  6451680.516600  1872771.288000     14.0     4.9
    2005-06-15 14:50:01  6451712.530000  1872744.872800     14.0     4.9
    2005-06-15 14:50:02  6451744.306900  1872718.384400     14.0     4.9
    2005-06-15 14:50:03  6451775.113500  1872692.352600     14.0     4.9
    2005-06-15 14:50:04  6451806.879000  1872664.945800     14.0     4.9
    2005-06-15 14:50:05  6451838.825100  1872637.237100     14.0     4.9
    2005-06-15 14:50:06  6451870.478300  1872610.178000     14.0     4.9
    2005-06-15 14:50:07  6451901.928700  1872583.713300     14.0     4.9
    2005-06-15 14:50:08  6451933.917100  1872555.400300     14.0     4.9
    2005-06-15 14:50:09  6451966.367100  1872527.416200     14.0     4.9
    2005-06-15 14:50:10  6451999.070600  1872498.523400     14.0     4.9
    2005-06-15 14:50:11  6452032.807100  1872467.603700     14.0     4.9
    2005-06-15 14:50:12  6452066.657600  1872437.888100     14.0     4.9
    2005-06-15 14:50:13  6452100.505100  1872408.238700     14.0     4.9
    2005-06-15 14:50:14  6452134.949700  1872377.870500     14.0     4.9
    2005-06-15 14:50:15  6452171.797400  1872345.135700     14.0     4.9
    2005-06-15 14:50:16  6452208.437900  1872313.835700     14.0     4.9
    2005-06-15 14:50:17  6452244.675200  1872282.472800     14.0     4.9
    2005-06-15 14:50:18  6452282.068200  1872250.729600     14.0     4.9
    2005-06-15 14:50:19  6452319.387700  1872219.059000     14.0     4.9
    2005-06-15 14:50:20  6452357.065800  1872185.975100     14.0     4.9
    2005-06-15 14:50:21  6452394.768300  1872152.202300     14.0     4.9
    2005-06-15 14:50:22  6452433.272900  1872118.231400     14.0     4.9
    2005-06-15 14:50:23  6452474.516100  1872082.188200     14.0     4.9
    2005-06-15 14:50:24  6452516.763900  1872044.113300     14.0     4.9
    2005-06-15 14:50:25  6452559.296300  1872008.186900     14.0     4.9
    2005-06-15 14:50:26  6452602.654000  1871970.617000     14.0     4.9
    2005-06-15 14:50:27  6452646.343000  1871935.321900     14.0     4.9
    2005-06-15 14:50:28  6452685.030286  1871905.380000     14.0     4.9

                         vType      veloc     accel  line  pred  foll    spac  \
vID dateTime
2   2005-06-15 14:49:40      2  40.002500  0.031250   2.0   0.0   0.0   0.000
    2005-06-15 14:49:41      2  39.026000 -1.853000   2.0   0.0  11.7   0.000
    2005-06-15 14:49:42      2  35.444000 -2.795000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:43      2  38.113000  4.215000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:44      2  39.461000  0.598000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:45      2  39.882000  0.205000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:46      2  43.238000  3.943000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:47      2  44.858000 -0.376000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:48      2  45.404000  2.916000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:49      2  45.283000 -1.972000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:50      2  42.870000 -4.140000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:51      2  39.434000 -4.553000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:52      2  35.005000  0.267000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:53      2  35.510000 -0.446000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:54      2  37.734000  4.918000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:55      2  39.891000  0.670000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:56      2  43.209000  4.440000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:57      2  45.000000  0.000000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:58      2  47.360000  6.275000   2.0   0.0  13.0   0.000
    2005-06-15 14:49:59      2  49.574000 -4.008000   1.6   0.0  11.8   0.000
    2005-06-15 14:50:00      2  50.124000  1.663000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:01      2  50.024000  1.104000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:02      2  53.912000  6.474000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:03      2  57.466000  0.426000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:04      2  57.238000 -3.704000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:05      2  53.398000 -5.018000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:06      2  49.199000 -1.014000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:07      2  47.242000 -0.035000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:08      2  43.434000 -4.889000   1.0   0.0  10.0   0.000
    2005-06-15 14:50:09      2  40.679000 -1.014000   1.0   0.0  10.0   0.000
...                        ...        ...       ...   ...   ...   ...     ...
6   2005-06-15 14:49:59      2  44.811000 -4.032000   6.0   0.0  10.8   0.000
    2005-06-15 14:50:00      2  41.970000 -1.509000   6.0   0.0  18.0   0.000
    2005-06-15 14:50:01      2  41.707000  1.206000   5.5   2.0  16.0  27.492
    2005-06-15 14:50:02      2  40.061000 -1.939000   5.0   4.0  14.0  54.721
    2005-06-15 14:50:03      2  41.150000  1.830000   5.0   4.0  14.0  56.747
    2005-06-15 14:50:04      2  42.401000 -0.024000   5.0   4.0  14.0  55.683
    2005-06-15 14:50:05      2  42.047000 -0.855000   5.0   4.0  14.0  54.945
    2005-06-15 14:50:06      2  41.295000 -0.583000   5.0   4.0  14.0  57.046
    2005-06-15 14:50:07      2  41.423000  2.062000   5.0   4.0  14.0  60.047
    2005-06-15 14:50:08      2  43.778000 -0.235000   5.0   4.0  14.0  59.052
    2005-06-15 14:50:09      2  42.155000  0.572000   5.0   4.0  14.0  60.828
    2005-06-15 14:50:10      2  45.431000  3.154000   5.0   4.0  14.0  62.434
    2005-06-15 14:50:11      2  45.293000 -2.087000   5.0   4.0  14.0  62.630
    2005-06-15 14:50:12      2  44.902000  0.632000   5.0   4.0  14.0  64.403
    2005-06-15 14:50:13      2  45.042000  0.586000   5.0   4.0  14.0  66.039
    2005-06-15 14:50:14      2  48.007000  4.407000   5.0   4.0  14.0  67.357
    2005-06-15 14:50:15      2  49.465000 -2.606000   5.0   4.0  14.0  65.482
    2005-06-15 14:50:16      2  47.163000 -0.904000   5.0   4.0  14.0  65.844
    2005-06-15 14:50:17      2  48.566000  2.585000   5.0   4.0  14.0  66.604
    2005-06-15 14:50:18      2  49.060000  0.694000   5.0   4.0  14.0  68.158
    2005-06-15 14:50:19      2  49.930000  1.253000   5.0   4.0  14.0  67.749
    2005-06-15 14:50:20      2  49.773000 -0.221000   5.0   4.0  14.0  68.493
    2005-06-15 14:50:21      2  50.669000  1.756000   5.0   4.0  14.0  72.646
    2005-06-15 14:50:22      2  53.269000  2.632000   5.0   4.0  14.0  77.489
    2005-06-15 14:50:23      2  55.457000  1.730000   5.0   4.0  14.0  77.553
    2005-06-15 14:50:24      2  56.300000 -1.801000   5.0   4.0  14.0  75.212
    2005-06-15 14:50:25      2  55.266000  1.124000   5.0   4.0  14.0  74.823
    2005-06-15 14:50:26      2  56.359000 -2.856000   5.0   3.2  14.0  58.260
    2005-06-15 14:50:27      2  56.380000  3.739000   5.0   0.0  14.0   0.000
    2005-06-15 14:50:28      2  57.262857 -3.014286   5.0   0.0  14.0   0.000

                         headway
vID dateTime
2   2005-06-15 14:49:40    0.000
    2005-06-15 14:49:41    0.000
    2005-06-15 14:49:42    0.000
    2005-06-15 14:49:43    0.000
    2005-06-15 14:49:44    0.000
    2005-06-15 14:49:45    0.000
    2005-06-15 14:49:46    0.000
    2005-06-15 14:49:47    0.000
    2005-06-15 14:49:48    0.000
    2005-06-15 14:49:49    0.000
    2005-06-15 14:49:50    0.000
    2005-06-15 14:49:51    0.000
    2005-06-15 14:49:52    0.000
    2005-06-15 14:49:53    0.000
    2005-06-15 14:49:54    0.000
    2005-06-15 14:49:55    0.000
    2005-06-15 14:49:56    0.000
    2005-06-15 14:49:57    0.000
    2005-06-15 14:49:58    0.000
    2005-06-15 14:49:59    0.000
    2005-06-15 14:50:00    0.000
    2005-06-15 14:50:01    0.000
    2005-06-15 14:50:02    0.000
    2005-06-15 14:50:03    0.000
    2005-06-15 14:50:04    0.000
    2005-06-15 14:50:05    0.000
    2005-06-15 14:50:06    0.000
    2005-06-15 14:50:07    0.000
    2005-06-15 14:50:08    0.000
    2005-06-15 14:50:09    0.000
...                          ...
6   2005-06-15 14:49:59    0.000
    2005-06-15 14:50:00    0.000
    2005-06-15 14:50:01    0.661
    2005-06-15 14:50:02    1.367
    2005-06-15 14:50:03    1.381
    2005-06-15 14:50:04    1.313
    2005-06-15 14:50:05    1.308
    2005-06-15 14:50:06    1.380
    2005-06-15 14:50:07    1.449
    2005-06-15 14:50:08    1.350
    2005-06-15 14:50:09    1.442
    2005-06-15 14:50:10    1.376
    2005-06-15 14:50:11    1.384
    2005-06-15 14:50:12    1.433
    2005-06-15 14:50:13    1.468
    2005-06-15 14:50:14    1.405
    2005-06-15 14:50:15    1.324
    2005-06-15 14:50:16    1.397
    2005-06-15 14:50:17    1.370
    2005-06-15 14:50:18    1.390
    2005-06-15 14:50:19    1.357
    2005-06-15 14:50:20    1.378
    2005-06-15 14:50:21    1.435
    2005-06-15 14:50:22    1.456
    2005-06-15 14:50:23    1.397
    2005-06-15 14:50:24    1.336
    2005-06-15 14:50:25    1.356
    2005-06-15 14:50:26    1.024
    2005-06-15 14:50:27    0.000
    2005-06-15 14:50:28    0.000

[162 rows x 17 columns]

In [58]:
num_v = data.groupby(['vID']).size()

In [59]:
num_v #foe vID how many times it appears

vID
2    437
4    351
5    452
6    357
dtype: int64

In [60]:
num_v.count() #num of different vehicles

4

In [61]:
data.describe()

,vID,frID,tFr,Timestamp,localX,localY,globalX,globalY,vLenght,vWidth,vType,veloc,accel,line,pred,foll,spac,headway
count,1597.000000,1597.000000,1597.000000,1.597000e+03,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000
mean,4.182843,267.204133,404.460238,1.118847e+12,40.166214,1114.140043,6451915.031800,1872594.324443,15.425485,5.749092,2,46.853181,0.427790,3.865373,0.706324,9.244208,11.302549,0.241935
std,1.496573,123.996664,45.413270,1.239967e+04,18.506289,559.918912,419.122022,372.802068,1.209852,1.351837,0,7.709628,4.989681,1.647519,1.525733,3.987194,24.613803,0.523286
min,2.000000,8.000000,351.000000,1.118847e+12,6.263000,35.381000,6451122.815000,1871894.687000,14.000000,4.900000,2,32.640000,-11.200000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,172.000000,357.000000,1.118847e+12,17.813000,664.639000,6451572.038000,1872291.603000,14.500000,4.900000,2,40.710000,-1.460000,2.000000,0.000000,6.000000,0.000000,0.000000
50%,5.000000,272.000000,437.000000,1.118847e+12,42.818000,1102.629000,6451903.487000,1872598.226000,16.000000,4.900000,2,45.000000,0.000000,4.000000,0.000000,8.000000,0.000000,0.000000
75%,5.000000,371.000000,452.000000,1.118847e+12,54.753000,1572.348000,6452258.323000,1872883.465000,17.000000,7.900000,2,51.360000,2.660000,5.000000,0.000000,13.000000,0.000000,0.000000
max,6.000000,497.000000,452.000000,1.118847e+12,71.498000,2161.090000,6452704.608000,1873344.962000,17.000000,7.900000,2,70.030000,11.200000,7.000000,4.000000,18.000000,78.580000,1.500000